spring.application.name=backend
server.port=${PORT:8085}

# Database Configuration (Hỗ trợ biến môi trường linh hoạt cho Docker/Cloud, fallback về Neon hoặc DB mặc định)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-aged-rain-aodwqqbp.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_xPbncO3Rdz0r}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
